export const answers = [
  { id: 1, answer: "4" },
  { id: 2, answer: "Indica a altura das notas, definindo a linha de referência para a partitura" },
  { id: 3, answer: "Ré" },
  { id: 4, answer: "Um símbolo que indica pausa ou silêncio na música" },
  { id: 5, answer: "7 notas" },
  { id: 6, answer: "Pianíssimo, ou seja, tocar muito suave" },
  { id: 7, answer: "Sustenido (#) eleva a nota em meio tom" },
  { id: 8, answer: "Bemol (b) abaixa a nota em meio tom" },
  { id: 9, answer: "Duração de um tempo no compasso" },
  { id: 10, answer: "Nota que vale metade de uma semínima" },
  { id: 11, answer: "Uma divisão do tempo na música, que organiza as batidas" },
  { id: 12, answer: "Uma sequência ordenada de notas musicais" },
  { id: 13, answer: "Indica que deve ser tocado com intensidade alta" },
  { id: 14, answer: "Semibreve" },
  { id: 15, answer: "Uma clave que indica a posição da nota fá na partitura" },
  { id: 16, answer: "Indica aumento gradual da intensidade sonora" },
  { id: 17, answer: "Terça" },
  { id: 18, answer: "Pausa que dura um tempo" },
  { id: 19, answer: "Indica um andamento moderado, nem muito rápido nem lento" },
  { id: 20, answer: "A distância entre duas notas" },
  { id: 21, answer: "Intervalo de três graus entre duas notas" },
  { id: 22, answer: "Diferença na construção das notas: maior tem terça maior, menor tem terça menor" },
  { id: 23, answer: "Escala com intervalo específico de tons e semitons, começando pela tônica" },
  { id: 24, answer: "Escala menor com fórmula específica de tons e semitons, natural" },
  { id: 25, answer: "Tocar as notas de forma ligada, suave e contínua" },
  { id: 26, answer: "Conjunto de três ou mais notas tocadas simultaneamente" },
  { id: 27, answer: "Três notas" },
  { id: 28, answer: "Acorde formado por três notas, geralmente tônica, terça e quinta" },
  { id: 29, answer: "Diminuição gradual da intensidade sonora" },
  { id: 30, answer: "Ritmo que valoriza o contratempo" },
  { id: 31, answer: "Compasso formado por subdivisões ternárias, como 6/8" },
  { id: 32, answer: "Semínima pontuada vale 1,5 tempos; semínima normal vale 1 tempo" },
  { id: 33, answer: "Nota que é ligada à nota seguinte sem interrupção" },
  { id: 34, answer: "Escala com cinco notas por oitava" },
  { id: 35, answer: "Mudança de tonalidade durante a música" },
  { id: 36, answer: "Acorde onde a terça é substituída por quarta ou segunda" },
  { id: 37, answer: "Conjunto de sustenidos ou bemóis no início da partitura indicando a tonalidade" },
  { id: 38, answer: "Escala formada por todos os semitons em uma oitava" },
  { id: 39, answer: "Função de resolver para a tônica, criando tensão" },
  { id: 40, answer: "Intervalo formado por cinco notas, considerado estável" },
  { id: 41, answer: "Motivo ou frase musical que se repete constantemente" },
  { id: 42, answer: "Cadência que termina em tônica, dando sensação de finalização" },
  { id: 43, answer: "Escala menor com sétimo grau elevado" },
  { id: 44, answer: "Escala menor com sexto e sétimo graus elevados na subida" },
  { id: 45, answer: "Mudança da posição das notas de um acorde" },
  { id: 46, answer: "Sinal que indica pausa prolongada numa nota ou pausa" },
  { id: 47, answer: "Intervalo que causa tensão, não harmônico" },
  { id: 48, answer: "Escalas derivadas de modos gregos, como dórico, frígio etc." },
  { id: 49, answer: "Acorde maior tem terça maior, acorde menor com sétima tem terça menor e sétima menor" },
  { id: 50, answer: "Textura musical com múltiplas linhas melódicas independentes" }
];
