export const questions = [
  { id: 1, question: "Quantos tempos tem um compasso 4/4?" },
  { id: 2, question: "O que significa a clave de Sol numa partitura?" },
  { id: 3, question: "Qual é o nome da nota que vem depois do Dó na escala musical?" },
  { id: 4, question: "O que é uma pausa em uma partitura?" },
  { id: 5, question: "Quantas notas existem na escala diatônica?" },
  { id: 6, question: "O que significa a abreviação “pp” na música?" },
  { id: 7, question: "Qual é o símbolo que indica uma nota sustenida (#)?" },
  { id: 8, question: "O que indica o símbolo de bemol (b)?" },
  { id: 9, question: "Qual é a duração de uma semínima?" },
  { id: 10, question: "O que é uma colcheia?" },
  { id: 11, question: "O que é um compasso?" },
  { id: 12, question: "O que é uma escala musical?" },
  { id: 13, question: "O que significa o termo “forte” na música?" },
  { id: 14, question: "Como se chama a nota que dura o dobro de uma semínima?" },
  { id: 15, question: "O que é uma clave de fá?" },
  { id: 16, question: "O que indica o símbolo “crescendo”?" },
  { id: 17, question: "Qual é a distância entre Dó e Mi?" },
  { id: 18, question: "O que é uma pausa de semínima?" },
  { id: 19, question: "O que significa a palavra “andante”?" },
  { id: 20, question: "O que é um intervalo musical?" },
  { id: 21, question: "O que é um intervalo de terça?" },
  { id: 22, question: "Qual a diferença entre uma nota maior e uma menor?" },
  { id: 23, question: "O que é uma escala maior?" },
  { id: 24, question: "O que é uma escala menor natural?" },
  { id: 25, question: "O que significa o termo “legato”?" },
  { id: 26, question: "O que é um acorde?" },
  { id: 27, question: "Quantas notas formam um acorde maior?" },
  { id: 28, question: "O que é uma tríade?" },
  { id: 29, question: "O que indica o símbolo “diminuendo”?" },
  { id: 30, question: "O que é um ritmo sincopado?" },
  { id: 31, question: "O que é um compasso composto?" },
  { id: 32, question: "Qual a diferença entre uma semínima pontuada e uma semínima normal?" },
  { id: 33, question: "O que é uma nota ligada?" },
  { id: 34, question: "O que é uma escala pentatônica?" },
  { id: 35, question: "O que é uma modulação musical?" },
  { id: 36, question: "O que é um acorde suspenso (sus4 ou sus2)?" },
  { id: 37, question: "O que significa “armadura de clave”?" },
  { id: 38, question: "O que é uma escala cromática?" },
  { id: 39, question: "Qual a função da dominante em uma progressão harmônica?" },
  { id: 40, question: "O que é um intervalo de quinta justa?" },
  { id: 41, question: "O que significa o termo “ostinato”?" },
  { id: 42, question: "O que é uma cadência perfeita?" },
  { id: 43, question: "O que é uma escala menor harmônica?" },
  { id: 44, question: "O que é uma escala menor melódica?" },
  { id: 45, question: "O que é uma inversão de acorde?" },
  { id: 46, question: "O que significa o símbolo “fermata”?" },
  { id: 47, question: "O que é um intervalo dissonante?" },
  { id: 48, question: "O que é uma escala modal?" },
  { id: 49, question: "Qual a diferença entre um acorde maior e um acorde menor com sétima?" },
  { id: 50, question: "O que é uma textura polifônica?" }
];


export async function getRandomQuestions (allQuestions: any, count = 5) {
  const shuffled = allQuestions.sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
}

